cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
spring:
  application:
    name: 01-rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1j86Ffcg1sn0lf5782
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

    open-in-view: false

  logging:
    level:
#      root: WARM
      br.com.augustoomb: DEBUG
      #NIVEL DEBUG ESCOLHIDO PARA VER COM DETALHES (USAR APENAS EM AMBIENTE DE DESENV)
      # OPÇÕES SÃO: TRACE, DEBUG(IDEAL PARA DEV, SE PRECISAR VERIFICAR), INFO(PADRÃO), WARM(IDEAL PRODUÇÃO), ERROR
      # AS OPÇÕES SÃO NÍVEIS, OU SEJA, TRACE PEGA TODOS OS OUTROS, DEBUG PEGA DELE ATÉ ERROR, ETC
      # LEMBRANDO QUE QUANTO MAIS PRA "BAIXO", MAIS RECURSOS SÃO GASTOS (TRACE GASTA MAIS)


  # O QUE O SWAGGER TERÁ ACESSO PARA GERAR A DOC:
  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true